# Generated by Django 3.1.7 on 2021-04-05 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documentos', '0002_auto_20210405_0937'),
    ]

    operations = [
        migrations.RenameField(
            model_name='documento',
            old_name='done',
            new_name='tipo',
        ),
    ]
