# Generated by Django 3.1.7 on 2021-04-06 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentos', '0004_documento_pdf'),
    ]

    operations = [
        migrations.CreateModel(
            name='EDocModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=80)),
                ('pdf', models.FileField(upload_to='pdfs/')),
            ],
            options={
                'ordering': ['title'],
            },
        ),
        migrations.RemoveField(
            model_name='documento',
            name='pdf',
        ),
    ]
