# Generated by Django 3.1.7 on 2021-04-08 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentos', '0007_pasta_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='pasta',
            name='NomeDoc',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pasta',
            name='nomePdf',
            field=models.FileField(default=1, upload_to='pdfs/'),
            preserve_default=False,
        ),
    ]
