# Generated by Django 3.1.7 on 2021-04-09 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentos', '0008_auto_20210408_0944'),
    ]

    operations = [
        migrations.AddField(
            model_name='edocmodel',
            name='pasta',
            field=models.ManyToManyField(related_name='_edocmodel_pasta_+', to='documentos.Pasta'),
        ),
    ]
